import type { Prisma, PrismaClient } from "@prisma/client";
import { canManageAthlete, type AuthenticatedUser } from "@/lib/auth/authorization";
import { generateSessionOccurrences } from "./dates";
import { ProgrammeError } from "./errors";
import { exerciseSlotPrescriptionSchema, type ExerciseSlotPrescriptionInput } from "./schema";

type Db = PrismaClient | Prisma.TransactionClient;
const blockGraph = { athlete: { include: { user: true } }, weeks: { orderBy: { weekNumber: "asc" as const }, include: { sessions: { orderBy: [{ scheduledAt: "asc" as const }, { sessionNumber: "asc" as const }], include: { exercises: { orderBy: { orderIndex: "asc" as const }, include: { exercise: true, setPrescriptions: { orderBy: { setNumber: "asc" as const } } } } } } } } };

export class ProgrammeService {
  constructor(private readonly db: PrismaClient) {}
  private async athleteForManager(actor: AuthenticatedUser, athleteId: string) { const athlete = await this.db.athlete.findUnique({ where: { id: athleteId } }); if (!athlete || !canManageAthlete(actor, athlete)) throw new ProgrammeError("Athlete not found", 404); return athlete; }
  private async draftForManager(actor: AuthenticatedUser, blockId: string) { const block = await this.db.block.findUnique({ where: { id: blockId }, include: { athlete: true } }); if (!block || !canManageAthlete(actor, block.athlete)) throw new ProgrammeError("Block not found", 404); if (block.status !== "DRAFT" || block.frozenAt) throw new ProgrammeError("Only an unfrozen draft programme can be edited", 409); return block; }
  async createDraftBlock(actor: AuthenticatedUser, input: { athleteId: string; name: string; phase?: string | null; startDate: Date; weekCount: number; sessionsPerWeek: number; deloadType?: string | null; intensityTrend?: string | null; volumeTrend?: string | null; applyProgression: boolean; notes?: string | null }) {
    const athlete = await this.athleteForManager(actor, input.athleteId);
    const settings = await this.db.userSettings.findUnique({ where: { userId: athlete.userId } });
    if (!settings || settings.trainingDays.length < input.sessionsPerWeek) throw new ProgrammeError("Configure enough ordered athlete training days before creating a block");
    const occurrences = generateSessionOccurrences({ startDate: input.startDate, trainingDays: settings.trainingDays, sessionsPerWeek: input.sessionsPerWeek, weekCount: input.weekCount });
    const endDate = occurrences.at(-1)?.scheduledAt ?? input.startDate;
    return this.db.$transaction(async (tx) => {
      const block = await tx.block.create({ data: { athleteId: athlete.id, coachId: actor.role === "COACH" ? actor.coachProfile!.id : null, title: input.name, phase: input.phase, startDate: input.startDate, endDate, weekCount: input.weekCount, sessionsPerWeek: input.sessionsPerWeek, status: "DRAFT", deloadType: input.deloadType, intensityTrend: input.intensityTrend, volumeTrend: input.volumeTrend, applyProgression: input.applyProgression, notes: input.notes } });
      await this.generateDatedSessions(tx, block.id, occurrences);
      return tx.block.findUniqueOrThrow({ where: { id: block.id }, include: blockGraph });
    });
  }
  private async generateDatedSessions(tx: Db, blockId: string, occurrences: ReturnType<typeof generateSessionOccurrences>) { for (const weekNumber of [...new Set(occurrences.map((o) => o.programmeWeek))]) { const rows = occurrences.filter((o) => o.programmeWeek === weekNumber); const week = await tx.week.create({ data: { blockId, weekNumber, startDate: rows[0].scheduledAt, endDate: rows.at(-1)!.scheduledAt } }); await tx.session.createMany({ data: rows.map((row) => ({ weekId: week.id, sessionNumber: row.sessionNumber, sessionCode: row.sessionCode, trainingDay: row.trainingDay, dayOfWeek: row.trainingDay, title: `Session ${row.sessionNumber}`, scheduledAt: row.scheduledAt, status: "PLANNED" })) }); } }
  async getBlock(actor: AuthenticatedUser, blockId: string) { const block = await this.db.block.findUnique({ where: { id: blockId }, include: blockGraph }); if (!block || !canManageAthlete(actor, block.athlete)) throw new ProgrammeError("Block not found", 404); return block; }
  async listAthleteBlocks(actor: AuthenticatedUser, athleteId: string) { await this.athleteForManager(actor, athleteId); return this.db.block.findMany({ where: { athleteId }, orderBy: { createdAt: "desc" } }); }
  async updateDraftBlock(actor: AuthenticatedUser, blockId: string, data: Prisma.BlockUpdateInput) { await this.draftForManager(actor, blockId); return this.db.block.update({ where: { id: blockId }, data }); }
  async updateSession(actor: AuthenticatedUser, sessionId: string, data: { title?: string; notes?: string | null; trainingDay?: string; scheduledAt?: Date }) { const row = await this.db.session.findUnique({ where: { id: sessionId }, include: { week: { include: { block: true } } } }); if (!row) throw new ProgrammeError("Session not found", 404); await this.draftForManager(actor, row.week.blockId); return this.db.session.update({ where: { id: sessionId }, data: { ...data, dayOfWeek: data.trainingDay } }); }
  async addExerciseSlot(actor: AuthenticatedUser, sessionId: string, raw: ExerciseSlotPrescriptionInput) { const input = exerciseSlotPrescriptionSchema.parse(raw); const { exerciseId: selectedExerciseId, ...prescription } = input; void selectedExerciseId; const session = await this.db.session.findUnique({ where: { id: sessionId }, include: { week: { include: { block: true } } } }); if (!session) throw new ProgrammeError("Session not found", 404); const block = await this.draftForManager(actor, session.week.blockId); const exercise = await this.db.exercise.findFirst({ where: { id: input.exerciseId, athleteId: block.athleteId, active: true } }); if (!exercise) throw new ProgrammeError("Active exercise is not owned by this athlete", 400); return this.db.$transaction(async (tx) => { const last = await tx.exerciseSlot.aggregate({ where: { sessionId }, _max: { orderIndex: true } }); const slot = await tx.exerciseSlot.create({ data: { sessionId, exerciseId: exercise.id, name: exercise.name, orderIndex: (last._max.orderIndex ?? 0) + 1, ...prescription, targetSets: input.setCount, exerciseType: input.setType } }); await this.syncPlannedSets(tx, slot.id, input.setCount); return tx.exerciseSlot.findUniqueOrThrow({ where: { id: slot.id }, include: { exercise: true, setPrescriptions: { orderBy: { setNumber: "asc" } } } }); }); }
  async updateExerciseSlot(actor: AuthenticatedUser, slotId: string, raw: ExerciseSlotPrescriptionInput) { const input = exerciseSlotPrescriptionSchema.parse(raw); const existing = await this.db.exerciseSlot.findUnique({ where: { id: slotId }, include: { session: { include: { week: true } } } }); if (!existing) throw new ProgrammeError("Exercise slot not found", 404); const block = await this.draftForManager(actor, existing.session.week.blockId); const exercise = await this.db.exercise.findFirst({ where: { id: input.exerciseId, athleteId: block.athleteId } }); if (!exercise) throw new ProgrammeError("Exercise is not owned by this athlete", 400); return this.db.$transaction(async (tx) => { await tx.exerciseSlot.update({ where: { id: slotId }, data: { ...input, name: exercise.name, targetSets: input.setCount, exerciseType: input.setType } }); await this.syncPlannedSets(tx, slotId, input.setCount); return tx.exerciseSlot.findUniqueOrThrow({ where: { id: slotId }, include: { setPrescriptions: { orderBy: { setNumber: "asc" } } } }); }); }
  async duplicateExerciseSlot(actor: AuthenticatedUser, slotId: string) { const source = await this.db.exerciseSlot.findUnique({ where: { id: slotId }, include: { session: { include: { week: true } } } }); if (!source) throw new ProgrammeError("Exercise slot not found", 404); await this.draftForManager(actor, source.session.week.blockId); return this.db.$transaction(async (tx) => { const following = await tx.exerciseSlot.findMany({ where: { sessionId: source.sessionId, orderIndex: { gt: source.orderIndex } }, orderBy: { orderIndex: "desc" } }); for (const row of following) await tx.exerciseSlot.update({ where: { id: row.id }, data: { orderIndex: row.orderIndex + 1 } }); const { id, createdAt, updatedAt, session: includedSession, ...copy } = source; void id; void createdAt; void updatedAt; void includedSession; const slot = await tx.exerciseSlot.create({ data: { ...copy, orderIndex: source.orderIndex + 1 } }); await this.syncPlannedSets(tx, slot.id, slot.setCount); return slot; }); }
  async removeExerciseSlot(actor: AuthenticatedUser, slotId: string) { const slot = await this.db.exerciseSlot.findUnique({ where: { id: slotId }, include: { session: { include: { week: true } } } }); if (!slot) throw new ProgrammeError("Exercise slot not found", 404); await this.draftForManager(actor, slot.session.week.blockId); await this.db.exerciseSlot.delete({ where: { id: slotId } }); }
  async reorderExerciseSlots(actor: AuthenticatedUser, sessionId: string, orderedIds: string[]) { const session = await this.db.session.findUnique({ where: { id: sessionId }, include: { week: true, exercises: true } }); if (!session) throw new ProgrammeError("Session not found", 404); await this.draftForManager(actor, session.week.blockId); if (orderedIds.length !== session.exercises.length || new Set(orderedIds).size !== orderedIds.length || orderedIds.some((id) => !session.exercises.some((row) => row.id === id))) throw new ProgrammeError("Order must contain every slot exactly once"); await this.db.$transaction(async (tx) => { for (let i = 0; i < orderedIds.length; i++) await tx.exerciseSlot.update({ where: { id: orderedIds[i] }, data: { orderIndex: -(i + 1) } }); for (let i = 0; i < orderedIds.length; i++) await tx.exerciseSlot.update({ where: { id: orderedIds[i] }, data: { orderIndex: i + 1 } }); }); }
  async syncPlannedSets(tx: Db, slotId: string, setCount: number) { const existing = await tx.plannedSet.findMany({ where: { exerciseId: slotId }, orderBy: { setNumber: "asc" } }); const byNumber = new Set(existing.map((row) => row.setNumber)); for (let n = 1; n <= setCount; n++) if (!byNumber.has(n)) await tx.plannedSet.create({ data: { exerciseId: slotId, setNumber: n, status: "PLANNED" } }); await tx.plannedSet.deleteMany({ where: { exerciseId: slotId, setNumber: { gt: setCount }, status: "PLANNED" } }); }
}
