"use client";

import Link from "next/link";
import { Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

import { ExerciseDialog } from "@/components/exercises/ExerciseDialog";
import { ExerciseForm } from "@/components/exercises/ExerciseForm";
import { duplicateExercise, readApiError, setExerciseArchived, type ExerciseRecord } from "@/lib/exercises/client";

type Archived = "exclude" | "only";
const selectClass="min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/25";

function ExerciseLibraryPageContent(){
  const searchParams=useSearchParams(); const athleteId=searchParams.get("athleteId") || undefined;
  const [exercises,setExercises]=useState<ExerciseRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [q,setQ]=useState(""); const [mainLift,setMainLift]=useState(""); const [category,setCategory]=useState(""); const [equipment,setEquipment]=useState(""); const [capability,setCapability]=useState(""); const [eligible,setEligible]=useState(""); const [sort,setSort]=useState("name"); const [archived,setArchived]=useState<Archived>("exclude");
  const [editing,setEditing]=useState<ExerciseRecord|"new"|null>(null); const [duplicate,setDuplicate]=useState<ExerciseRecord|null>(null); const [duplicateName,setDuplicateName]=useState(""); const [actionError,setActionError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");const params=new URLSearchParams({archived,sort});if(athleteId)params.set("athleteId",athleteId);if(q.trim())params.set("q",q.trim());if(mainLift)params.set("mainLift",mainLift);if(category.trim())params.set("category",category.trim());if(equipment.trim())params.set("equipment",equipment.trim());if(capability)params.set("capability",capability);if(eligible)params.set("progressionEligibility",eligible);try{const r=await fetch(`/api/exercises?${params}`);if(!r.ok){setError((await readApiError(r)).message);return;}setExercises(await r.json() as ExerciseRecord[]);}catch{setError("Unable to reach the exercise library. Check your connection and try again.");}finally{setLoading(false);}},[archived,athleteId,capability,category,eligible,equipment,mainLift,q,sort]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),q?250:0);return()=>clearTimeout(timer);},[load,q]);
  const customCount=useMemo(()=>exercises.filter(x=>x.source==="CUSTOM").length,[exercises]);
  async function toggle(exercise:ExerciseRecord){if(exercise.active&&!window.confirm(`Archive ${exercise.name}? It will remain in training history and can be restored.`))return;setActionError("");try{await setExerciseArchived(exercise.id,exercise.active,athleteId);await load();}catch(requestError){setActionError((requestError as {message?:string}).message||"Unable to update the exercise.");}}
  async function submitDuplicate(){if(!duplicate)return;setActionError("");try{await duplicateExercise(duplicate.id,duplicateName,athleteId);setDuplicate(null);setDuplicateName("");await load();}catch(requestError){setActionError((requestError as {message?:string}).message||"Unable to duplicate the exercise.");}}
  return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900/70"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Link href={athleteId?"/dashboard":"/athlete/home"} className="font-bold tracking-tight">POWER<span className="text-cyan-400">COACH</span></Link><span className="text-sm text-slate-400">{athleteId?"Managing athlete library":"Your library"}</span></div></header>
  <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Library</p><h1 className="mt-1 text-3xl font-bold">Exercises</h1><p className="mt-2 max-w-2xl text-slate-400">Manage the live exercise definitions used for future programming. Training history always keeps its original references.</p></div><button onClick={()=>setEditing("new")} className="min-h-12 rounded-xl bg-cyan-400 px-5 font-semibold text-slate-950 hover:bg-cyan-300">+ New exercise</button></div>
  <section aria-label="Library controls" className="mt-7 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><label htmlFor="exercise-search" className="sr-only">Search exercise library</label><input id="exercise-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, movement, group or equipment…" className="min-h-12 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/25"/><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><label className="text-xs text-slate-400">Family<select aria-label="Main lift" value={mainLift} onChange={e=>setMainLift(e.target.value)} className={`${selectClass} mt-1 w-full`}><option value="">All</option>{["SQUAT","BENCH","DEADLIFT","ACCESSORY"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-slate-400">Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="All" className={`${selectClass} mt-1 w-full`}/></label><label className="text-xs text-slate-400">Equipment<input value={equipment} onChange={e=>setEquipment(e.target.value)} placeholder="All" className={`${selectClass} mt-1 w-full`}/></label><label className="text-xs text-slate-400">Capability<select value={capability} onChange={e=>setCapability(e.target.value)} className={`${selectClass} mt-1 w-full`}><option value="">All</option>{["LOADED_REPS","BODYWEIGHT_REPS","WEIGHTED_BODYWEIGHT","TIME"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="text-xs text-slate-400">Progression<select value={eligible} onChange={e=>setEligible(e.target.value)} className={`${selectClass} mt-1 w-full`}><option value="">All</option>{["YES","NO","OPTIONAL"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-slate-400">Status<select value={archived} onChange={e=>setArchived(e.target.value as Archived)} className={`${selectClass} mt-1 w-full`}><option value="exclude">Active</option><option value="only">Archived</option></select></label><label className="col-span-2 text-xs text-slate-400 sm:col-span-1">Sort<select value={sort} onChange={e=>setSort(e.target.value)} className={`${selectClass} mt-1 w-full`}><option value="name">Name</option><option value="mainLift">Main lift</option><option value="category">Category</option><option value="createdAt">Recently added</option></select></label></div></section>
  <div className="mt-5 flex items-center justify-between text-sm text-slate-400"><p aria-live="polite">{loading?"Loading…":`${exercises.length} ${archived==="only"?"archived":"active"} exercises`}</p>{!loading&&<p>{customCount} custom</p>}</div>{(error||actionError)&&<div role="alert" className="mt-4 rounded-xl border border-rose-800 bg-rose-950/40 p-4 text-rose-200">{error||actionError} <button onClick={()=>void load()} className="ml-2 underline">Retry</button></div>}
  {loading?<div role="status" className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(x=><div key={x} className="h-36 animate-pulse rounded-2xl bg-slate-900"/>)}</div>:!error&&exercises.length===0?<div className="mt-5 rounded-2xl border border-dashed border-slate-700 p-10 text-center"><h2 className="text-lg font-semibold">No exercises found</h2><p className="mt-1 text-slate-400">{q||mainLift||category||equipment||capability||eligible?"Try clearing your search or filters.":archived==="only"?"Archived exercises will appear here.":"Create your first custom exercise."}</p></div>:<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{exercises.map(exercise=><article key={exercise.id} className="flex flex-col rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{exercise.name}</h2><p className="mt-1 text-sm text-slate-400">{exercise.mainLift} · {exercise.category}</p></div><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${exercise.source==="CUSTOM"?"bg-cyan-950 text-cyan-300":"bg-slate-800 text-slate-400"}`}>{exercise.source}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-xs text-slate-500">Equipment</dt><dd>{exercise.equipment||"Needs review"}</dd></div><div><dt className="text-xs text-slate-500">Capability</dt><dd>{exercise.capability.replaceAll("_"," ")}</dd></div><div><dt className="text-xs text-slate-500">Movement</dt><dd>{exercise.movementPattern||"Needs review"}</dd></div><div><dt className="text-xs text-slate-500">Default</dt><dd>{exercise.defaultMode.replaceAll("_"," ")}</dd></div></dl><div className="mt-auto flex gap-2 pt-5"><button onClick={()=>setEditing(exercise)} className="min-h-11 flex-1 rounded-xl border border-slate-700 px-3 text-sm hover:bg-slate-800">Edit</button>{exercise.active&&<button onClick={()=>{setActionError("");setDuplicate(exercise);setDuplicateName(`${exercise.name} copy`)}} className="min-h-11 rounded-xl border border-slate-700 px-3 text-sm hover:bg-slate-800">Duplicate</button>}<button onClick={()=>void toggle(exercise)} className={`min-h-11 rounded-xl border px-3 text-sm ${exercise.active?"border-amber-700 text-amber-300":"border-emerald-700 text-emerald-300"}`}>{exercise.active?"Archive":"Restore"}</button></div></article>)}</div>}
  </div>
  {editing&&<ExerciseDialog label={editing==="new"?"Create exercise":"Edit exercise"} onClose={()=>setEditing(null)}><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">{editing==="new"?"Create":"Edit metadata"}</p><h2 className="text-2xl font-semibold">{editing==="new"?"New exercise":editing.name}</h2></div><ExerciseForm exercise={editing==="new"?undefined:editing} athleteId={athleteId} onCancel={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load();}}/></ExerciseDialog>}
  {duplicate&&<ExerciseDialog label="Duplicate exercise" onClose={()=>setDuplicate(null)}><h2 className="text-2xl font-semibold">Duplicate {duplicate.name}</h2><p className="mt-2 text-slate-400">All metadata will be copied into a new custom exercise. Enter a unique name.</p>{actionError&&<p role="alert" className="mt-3 text-rose-300">{actionError}</p>}<label className="mt-5 block text-sm">New exercise name *<input autoFocus value={duplicateName} onChange={e=>setDuplicateName(e.target.value)} className="mt-1 min-h-12 w-full rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setDuplicate(null)} className="min-h-11 rounded-xl border border-slate-700 px-4">Cancel</button><button disabled={!duplicateName.trim()} onClick={()=>void submitDuplicate()} className="min-h-11 rounded-xl bg-cyan-400 px-4 font-semibold text-slate-950 disabled:opacity-50">Create duplicate</button></div></ExerciseDialog>}
  </main>;
}

export default function ExerciseLibraryPage(){return <Suspense fallback={<main className="min-h-screen bg-slate-950 p-8 text-slate-300">Loading exercise library…</main>}><ExerciseLibraryPageContent/></Suspense>}
